name: interior_coffee
description: "Interior Design for Coffee Shops"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

#Package
dependencies:
  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.1
  build_runner: ^2.4.12
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.2
  iconsax: ^0.0.8
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  model_viewer_plus: ^1.9.0
  dio: ^5.7.0
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^4.2.1
  badges: ^3.1.0
  firebase_core:
  cloud_firestore:
  firebase_auth:
  google_sign_in:
  webview_flutter: ^4.10.0

#Package end
flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_lints: ^4.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  #Local assets
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/product/

    #Local fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
