// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGKApQvWkmZ3QuWWE0g_8z5tLLlUG2l7g',
    appId: '1:281519500110:web:d1d94bf5173d57da674c1f',
    messagingSenderId: '281519500110',
    projectId: 'interiorcoffee-4733b',
    authDomain: 'interiorcoffee-4733b.firebaseapp.com',
    storageBucket: 'interiorcoffee-4733b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1IFKqZd1popL4IHbCTjP45_YwtFHsZ-I',
    appId: '1:281519500110:android:ccddbbac333024ab674c1f',
    messagingSenderId: '281519500110',
    projectId: 'interiorcoffee-4733b',
    storageBucket: 'interiorcoffee-4733b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFQbqfsoYR0CtInnFwE4VcPhiXhQcsIR8',
    appId: '1:281519500110:ios:729d6125a0b6390c674c1f',
    messagingSenderId: '281519500110',
    projectId: 'interiorcoffee-4733b',
    storageBucket: 'interiorcoffee-4733b.firebasestorage.app',
    iosBundleId: 'com.example.interiorCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFQbqfsoYR0CtInnFwE4VcPhiXhQcsIR8',
    appId: '1:281519500110:ios:729d6125a0b6390c674c1f',
    messagingSenderId: '281519500110',
    projectId: 'interiorcoffee-4733b',
    storageBucket: 'interiorcoffee-4733b.firebasestorage.app',
    iosBundleId: 'com.example.interiorCoffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGKApQvWkmZ3QuWWE0g_8z5tLLlUG2l7g',
    appId: '1:281519500110:web:5b30c2936055ada0674c1f',
    messagingSenderId: '281519500110',
    projectId: 'interiorcoffee-4733b',
    authDomain: 'interiorcoffee-4733b.firebaseapp.com',
    storageBucket: 'interiorcoffee-4733b.firebasestorage.app',
  );
}
