// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgIM6KgoIqj5UmExuI_iL6lCElyLU_hcU',
    appId: '1:773160946196:web:2fb2009c37369fceb4b501',
    messagingSenderId: '773160946196',
    projectId: 'intericoffee-442da',
    authDomain: 'intericoffee-442da.firebaseapp.com',
    storageBucket: 'intericoffee-442da.appspot.com',
    measurementId: 'G-JGJVMBF75Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVZ2hZHyO9nwi2OudCHAZTg_BsCHKKXEM',
    appId: '1:773160946196:android:bc5ba70ba98edfe7b4b501',
    messagingSenderId: '773160946196',
    projectId: 'intericoffee-442da',
    storageBucket: 'intericoffee-442da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmkwNk_Jt10VludlKKCJRlGXSrBz0YL-g',
    appId: '1:773160946196:ios:2e061dfba5ffa204b4b501',
    messagingSenderId: '773160946196',
    projectId: 'intericoffee-442da',
    storageBucket: 'intericoffee-442da.appspot.com',
    androidClientId: '773160946196-0cs7ulgmk7qc2v7nekrvo9ccks7a8i0f.apps.googleusercontent.com',
    iosClientId: '773160946196-r8mh3hge8dhuuq8haeheihmijnh76v9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.interiorCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmkwNk_Jt10VludlKKCJRlGXSrBz0YL-g',
    appId: '1:773160946196:ios:2e061dfba5ffa204b4b501',
    messagingSenderId: '773160946196',
    projectId: 'intericoffee-442da',
    storageBucket: 'intericoffee-442da.appspot.com',
    androidClientId: '773160946196-0cs7ulgmk7qc2v7nekrvo9ccks7a8i0f.apps.googleusercontent.com',
    iosClientId: '773160946196-r8mh3hge8dhuuq8haeheihmijnh76v9t.apps.googleusercontent.com',
    iosBundleId: 'com.example.interiorCoffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdteJ_LLXuibEASWP8PqdgWE5kT4WFqow',
    appId: '1:773160946196:web:533814e7b1651920b4b501',
    messagingSenderId: '773160946196',
    projectId: 'intericoffee-442da',
    authDomain: 'intericoffee-442da.firebaseapp.com',
    storageBucket: 'intericoffee-442da.appspot.com',
    measurementId: 'G-900RLVWEC0',
  );

}